-- ORA-01031: insufficient privileges  = 불충분한 권한
CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);
-- TABLE에 데이터를 넣는 방법! -> 회원가입
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES('일용자', 11, 1, '서울시 중구');
-- 컬럼명 생략 가능!
INSERT INTO STUDENT_TBL VALUES('이용자', 22, 2, '서울시 종로구');
INSERT INTO STUDENT_TBL VALUES('삼용자', 33, 3, '서울시 동대문구');
INSERT INTO STUDENT_TBL VALUES('사용자', 44, 4, '서울시 서대문구');

UPDATE STUDENT_TBL
SET STUDENT_AGE = 99
WHERE STUDENT_GRADE = 2;

DELETE FROM STUDENT_TBL
WHERE STUDENT_GRADE = 2;

INSERT INTO STUDENT_TBL
VALUES(' ', 55, 5, NULL);
-- 데이터를 삭제해보자 -> 회원탈퇴
DELETE FROM STUDENT_TBL;





CREATE TABLE DATATYPE_TBL (
    MOONJJA CHAR(10), 
    -- 알파벳 10글자, 한글 3글자
    MOONJJAYUL VARCHAR2(100), 
    -- 알파벳 100글자, 한글 33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP
);